stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: phpmyadmin:${CICD_EXECUTION_SEQUENCE}         
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
